[project]
name = "data-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yash Gupta", email = "somgupta070703@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.3.18",
    "langchain-mistralai>=1.1.6",
    "langgraph>=1.2.11",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
data-agent = "data_agent:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
