from pydantic import BaseModel,Field,ConfigDict #basemodel and field tells it's using strict mode
from typing import Annotated, Literal
from operator import add


class AgentSchema(BaseModel):
    # model_config = ConfigDict(arbitrary_types_allowed=True) # Added configuration with the help of gemma
    # LLM's read all this - as a comlete context
    # ye description - AI model ke samajhne ke liye hai
    messages : Annotated[list,add] = Field(..., description="List of messages to be processed by the agent")
    user_question : str = Field(..., description="The original question asked by the user")
    curated_ques : str = Field(..., description="Curated user question")
    prompt_query_context : str = Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on the curated question and prompt context")
    is_safe : Literal["Yes","No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(..., description="Comments regarding the safety of the generated SQL query")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query on the database")
    final_answer : str = Field(..., description="The final answer generated by the agent based on the SQL query execution result and the curated question")



class JudgeSchema(BaseModel):
    # model_config = ConfigDict(arbitrary_types_allowed=True) # Added configuration for arbitrary types
    # will judge that the generated SQL query is safe to proceed or not
    # and add additional comment for their accent on that YES or NO

    answer : Literal["Yes","No"] = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")

