from pydantic import BaseModel,Field #basemodel and field tells it's using strict mode
from typing import Annotated, Literal
from operator import add


class AgentSchema(BaseModel):
    # LLM's read all this - as a comlete context
    # ye description - AI model ke samajhne ke liye hai
    messages : Annotated[list,add] = Field (...,description="List of messages to be processed by Agents.")
    user_question : str = Field(...,description="The original question asked by the user.")
    curated_ques : str = Field (...,description="List of curated user questions)")
    prompt_query_context : str = Field (...,description="A detailed prompt with SQL DB context for the prompt query that will help agent to generate SQL Query.")
    is_safe : Literal["Yes","No"] = Field(...,description="Whether the generated SQL query is safe to execute or not.")
    generated_sql_query : str = Field(...,description="The SQL query generated by the agent based on the prompt query context and curated questions.")
    sql_query_execution_result : str = Field(...,description="The result of executing the generated SQL query on the database.")
    final_answer : str = Field(...,description="The final answer generated by the agent based on the SQL query execution result and curated questions.")


class JudgeSchema(BaseModel):
    # will judge that the generated SQL query is safe to proceed or not
    # and add additional comment for their accent on that YES or NO

    answer : Literal = Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments : str = Field(..., description="Additional comments or feedback from the judge regarding the SQL query")